# -*- coding: utf-8 -*-
"""DLProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kKAlMUHxxY9O47jI1-rCjx2xmuyW-V3P
"""

!pip install dgl

import dgl
import pytorch

data = dgl.data.MiniGCDataset(num_graphs=100, min_num_v=32, max_num_v=33, seed=0)

len(data)

g, label = data[64]
g

for d in data:
    if d[0].num_nodes() != 32:
        print(d[0].num_nodes(), d[1])
        a = d[1]
    #assert d[0].num_nodes() == 16
    #assert d[0].num_edges() == 48

for d, l in data:
    if d.num_nodes() != 32:
        print(d.num_nodes())
    if l == a:
        print(d)

"""Quindi tutti e soli i grafi con label 5 non hanno 32 nodi, li rimuoviamo."""

